### PR TITLE
Try formatting ci.yml?

### PR DESCRIPTION
**Pull request by manzt**
I'm really perplexed with what is going on... (following the Actions - sorry you've been struggling through this!)

As a last ditch effort, I wonder if it could be some confusing yaml thing? I'm just sharing in case it _maybe_ could be some silent parsing issue. Doubtful... but maybe worth a try. I rant it through a formatter, and added `${{ }}` around the if expression.

### CODE REVIEW

**Comment by vsbuffalo** [comment]
I'm starting to wonder if this is a GitHub bug? Last night I broke up the CI so the release code is it's own YAML file, but the action runner still displays the old DAG and shows the wrong code:

Screenshot 2024-11-08 at 8 38 17 AM

**Comment by manzt** [comment]
Wow, this is just so odd. You definitely deserve something for fighting with CI just to find out it could be GitHub itself...

I wonder, are there any caches in the Actions tab that you could clear?

**Comment by manzt** [comment]
> Last night I broke up the CI so the release code is it's own YAML file.

I see, did the separate `release.yml` succeed, is the correct "Workflow file" discovered there?

**Comment by manzt** [comment]
Ah! The `release.yml` one failed for: `

```

Error
No event triggers defined in `on`

```

maybe need to add an on to it?

**Comment by manzt** [comment]
~Maybe renaming the `ci.yml` would get you out of this loop. So odd.~

Wait, you know what! 

I wonder if you need to delete the previous release (and _tag_) and create a new _tag_ from the latest commit and cut a new release. I see the `ci.yml` that the "Workflow file" is from the release (sha [c7412b0](https://github.com/vsbuffalo/grid_df/releases/tag/v0.1.2)).

- https://github.com/vsbuffalo/grid_df/blob/c7412b0b33f12790c7a58f3a068f1bbcb3fe994d/.github/workflows/ci.yml

If that's how `release` triggers work, very surprising. But maybe we keep failing because we are reusing the same (old) tag to create new releases.

**Comment by manzt** [comment]
Ok, I'm nearly certain this is the issue. The [`GITHUB_SHA`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release) for `release` is "Last commit in the tagged release". I think this means that GitHub Actions will run the workflow file as it existed in the tagged commit.

I think you need a new re-tag and release for the fixed workflow to take effect. 

TIL - my first time using `release` trigger!

**Comment by vsbuffalo** [comment]
I can't quite tell what worked, but I (1) cleared out all past failed actions (2) deleted releases (which I had been doing before) and tags (which I hadn't been doing) and it seems to have finally worked. Thanks so much for your help @manzt!!

**Comment by manzt** [comment]
Hooray, happy it all got sorted out.

**Pull request merged**
